title: Scaldi
description: "Scaldi - Lightweight Dependency Injection Library"
baseurl: ""
url: "http://scaldi.org"
theme: flatly
ga-code: UA-41090613-1
domain: scaldi.org

version:
  scaldi: 0.5.1
  scaldi-play: 0.5.1
  scaldi-akka: 0.5.1

version-210:
  scaldi: 0.3.2
  scaldi-play: 0.3.3
  scaldi-akka: 0.3.3

link:
  scaldi-github: https://github.com/scaldi
  scaldi-maven: http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.scaldi%22
  scaldi-releases: https://github.com/scaldi/scaldi/releases
  scaldi-play-releases: https://github.com/scaldi/scaldi-play/releases
  scaldi-akka-releases: https://github.com/scaldi/scaldi-akka/releases
  scaldi-play-example-github: https://github.com/scaldi/scaldi-play-example
  scaldi-play-example-template: https://typesafe.com/activator/template/scaldi-play-example
  scaldi-play-example-blog: http://hacking-scala.org/post/51407241538/easy-dependency-injection-in-play-framework-with-scaldi
  scaldi-akka-example-github: https://github.com/scaldi/scaldi-akka-example
  scaldi-akka-example-template: https://typesafe.com/activator/template/scaldi-akka-example
  scaldi-akka-example-blog: http://hacking-scala.org/post/79931102837/dependency-injection-in-akka-with-scaldi
  scaldi-presentation: http://scaldi.github.io/scaldi-presentation
  twitter: https://twitter.com/easyangel
  stack-overflow: http://stackoverflow.com/questions/tagged/scaldi
  stack-overflow-ask: http://stackoverflow.com/questions/ask?tags=scala,scaldi
  google-groups: https://groups.google.com/forum/#!forum/scaldi
  scaldi-changelog: https://github.com/scaldi/scaldi/blob/master/CHANGELOG.md
  blog: http://hacking-scala.org/
  scaladoc:
    scaldi: http://scaldi.github.io/scaldi/latest/api
    scaldi-play: http://scaldi.github.io/scaldi-play/latest/api/#scaldi.play.ScaldiSupport
    scaldi-akka: http://scaldi.github.io/scaldi-akka/latest/api
  repo:
    scaldi: https://github.com/scaldi/scaldi
    scaldi-play: https://github.com/scaldi/scaldi-play
    scaldi-akka: https://github.com/scaldi/scaldi-akka
  maven:
    scaldi: http://search.maven.org/#artifactdetails%7Corg.scaldi%7Cscaldi_
    scaldi-play: http://search.maven.org/#artifactdetails%7Corg.scaldi%7Cscaldi-play_
    scaldi-akka: http://search.maven.org/#artifactdetails%7Corg.scaldi%7Cscaldi-akka_
  issues:
    scaldi: https://github.com/scaldi/scaldi/issues
    scaldi-play: https://github.com/scaldi/scaldi-play/issues
    scaldi-akka: https://github.com/scaldi/scaldi-akka/issues
  website: https://github.com/scaldi/scaldi-website
  jekyll: http://jekyllrb.com/
  ghpages: https://pages.github.com/

markdown: kramdown
permalink: pretty

gems:
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
